[project]
name = "compression-kit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keras>=3.12.0",
    "numpy>=2.3.4",
    "tensorflow>=2.18.0,<3.0",
    "tensorflow-metal>=1.1.0,<2.0; sys_platform == 'darwin'",
]
